schema_version: 1

context:
  name: datasketches
  version: 5.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/datasketches-${{ version }}.tar.gz
  sha256: c00d61da4695e00036e63f590999f584cc39246cbb147b171f375f792604a612

build:
  number: 2
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: numpy
  host:
    - python
    - wheel
    - setuptools >=30.3.0
    - cmake >=3.16
    - numpy <2.0
    - nanobind >=1.6
    - pip
    - make
  #- pybind11 >=2.6.0
  run:
    - python
    - ${{ pin_compatible('numpy') }}

tests:
  - python:
      imports:
        - datasketches
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: The Apache DataSketches Library for Python
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  homepage: http://datasketches.apache.org
  repository: https://github.com/apache/datasketches-cpp/tree/master/python

extra:
  recipe-maintainers:
    - rxm7706
